=== AMPW-german/XPathPatch/XPP.Tests/TestData/XPath.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="TokenType" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Attr" />
      <xs:enumeration value="Axis" />
      <xs:enumeration value="POpen" />
      <xs:enumeration value="BOpen" />
      <xs:enumeration value="PClose" />
      <xs:enumeration value="BClose" />
      <xs:enumeration value="Self" />
      <xs:enumeration value="Parent" />
      <xs:enumeration value="Comma" />
      <xs:enumeration value="OpAnd" />
      <xs:enumeration value="OpOr" />
      <xs:enumeration value="OpMod" />
      <xs:enumeration value="OpDiv" />
      <xs:enumeration value="OpMult" />
      <xs:enumeration value="OpSep" />
      <xs:enumeration value="OpSepDesc" />
      <xs:enumeration value="OpUnion" />
      <xs:enumeration value="OpAdd" />
      <xs:enumeration value="OpSub" />
      <xs:enumeration value="OpEq" />
      <xs:enumeration value="OpNeq" />
      <xs:enumeration value="OpLt" />
      <xs:enumeration value="OpLte" />
      <xs:enumeration value="OpGt" />
      <xs:enumeration value="OpGte" />
      <xs:enumeration value="NtAny" />
      <xs:enumeration value="NtAnyNs" />
      <xs:enumeration value="NtName" />
      <xs:enumeration value="NodeType" />
      <xs:enumeration value="FuncName" />
      <xs:enumeration value="AxisName" />
      <xs:enumeration value="String" />
      <xs:enumeration value="Number" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AstType" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Root" />
      <xs:enumeration value="Sep" />
      <xs:enumeration value="Axis" />
      <xs:enumeration value="NodeTest" />
      <xs:enumeration value="ProcType" />
      <xs:enumeration value="PathFilter" />
      <xs:enumeration value="ExprFilter" />
      <xs:enumeration value="Value" />
      <xs:enumeration value="FuncCall" />
      <xs:enumeration value="ArgList" />
      <xs:enumeration value="Union" />
      <xs:enumeration value="BoolOp" />
      <xs:enumeration value="CompareOp" />
      <xs:enumeration value="MathOp" />
      <xs:enumeration value="Negate" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="LibraryFunc" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Last" />
      <xs:enumeration value="Position" />
      <xs:enumeration value="Count" />
      <xs:enumeration value="Id" />
      <xs:enumeration value="LocalName" />
      <xs:enumeration value="NamespaceUri" />
      <xs:enumeration value="Name" />
      <xs:enumeration value="String" />
      <xs:enumeration value="Concat" />
      <xs:enumeration value="StartsWith" />
      <xs:enumeration value="Contains" />
      <xs:enumeration value="SubstringBefore" />
      <xs:enumeration value="SubstringAfter" />
      <xs:enumeration value="Substring" />
      <xs:enumeration value="StringLength" />
      <xs:enumeration value="NormalizeSpace" />
      <xs:enumeration value="Translate" />
      <xs:enumeration value="Boolean" />
      <xs:enumeration value="Not" />
      <xs:enumeration value="True" />
      <xs:enumeration value="False" />
      <xs:enumeration value="Lang" />
      <xs:enumeration value="Number" />
      <xs:enumeration value="Sum" />
      <xs:enumeration value="Floor" />
      <xs:enumeration value="Ceiling" />
      <xs:enumeration value="Round" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AxisType" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ancestor" />
      <xs:enumeration value="AncestorOrSelf" />
      <xs:enumeration value="Attribute" />
      <xs:enumeration value="Child" />
      <xs:enumeration value="Descendant" />
      <xs:enumeration value="DescendantOrSelf" />
      <xs:enumeration value="Following" />
      <xs:enumeration value="FollowingSibling" />
      <xs:enumeration value="Namespace" />
      <xs:enumeration value="Parent" />
      <xs:enumeration value="Preceding" />
      <xs:enumeration value="PrecedingSibling" />
      <xs:enumeration value="Self" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NodeType" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Comment" />
      <xs:enumeration value="Text" />
      <xs:enumeration value="ProcessingInstruction" />
      <xs:enumeration value="Node" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CExprType" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Path" />
      <xs:enumeration value="Constant" />
      <xs:enumeration value="Negate" />
      <xs:enumeration value="Logic" />
      <xs:enumeration value="Compare" />
      <xs:enumeration value="Math" />
      <xs:enumeration value="Func" />
      <xs:enumeration value="Variable" />
      <xs:enumeration value="UserFunc" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CPathType" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Context" />
      <xs:enumeration value="Root" />
      <xs:enumeration value="Reverse" />
      <xs:enumeration value="Dedupe" />
      <xs:enumeration value="Union" />
      <xs:enumeration value="Expr" />
      <xs:enumeration value="NodeType" />
      <xs:enumeration value="NameTest" />
      <xs:enumeration value="Filter" />
      <xs:enumeration value="Axis" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="XPType" final="restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Document" />
      <xs:enumeration value="Element" />
      <xs:enumeration value="Text" />
      <xs:enumeration value="CData" />
      <xs:enumeration value="ProcInst" />
      <xs:enumeration value="Comment" />
      <xs:enumeration value="Attribute" />
      <xs:enumeration value="Namespace" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="TestData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Entry" type="XPathEntry" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="XPathEntry">
    <xs:sequence>
      <xs:element name="Tokenize" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Tok" type="XPathTok" minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Parse" type="XPathAst" minOccurs="0" maxOccurs="1" />
      <xs:element name="Compile" type="XPathCExpr" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:ID" use="required" />
    <xs:attribute name="Expr" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="XPathTok">
    <xs:attribute name="T" type="TokenType" use="required" />
    <xs:attribute name="V" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="XPathAst">
    <xs:sequence>
      <xs:element name="L" type="XPathAst" minOccurs="0" maxOccurs="1" />
      <xs:element name="R" type="XPathAst" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="T" type="AstType" use="required" />
    <xs:attribute name="V" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="XPathCExpr">
    <xs:sequence>
      <xs:element name="Path" type="XPathCPath" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="L" type="XPathCExpr" minOccurs="0" />
      <xs:element name="R" type="XPathCExpr" minOccurs="0" />
      <xs:element name="Arg" type="XPathCExpr" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="T" type="CExprType" use="required" />
    <xs:attribute name="Str" type="xs:string" />
    <xs:attribute name="Num" type="xs:double" />
    <xs:attribute name="Op" type="TokenType" />
    <xs:attribute name="Fn" type="LibraryFunc" />
  </xs:complexType>
  <xs:complexType name="XPathCPath">
    <xs:sequence>
      <xs:element name="UL" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Path" type="XPathCPath" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="UR" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Path" type="XPathCPath" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Expr" minOccurs="0" type="XPathCExpr" />
    </xs:sequence>
    <xs:attribute name="T" type="CPathType" use="required" />
    <xs:attribute name="Fwd" type="xs:boolean" />
    <xs:attribute name="Ax" type="AxisType" />
    <xs:attribute name="Pt" type="XPType" />
    <xs:attribute name="Nt" type="NodeType" />
    <xs:attribute name="Ns" type="xs:string" />
    <xs:attribute name="N" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== AMPW-german/XPathPatch/XPP.Tests/TestData/XPath.xml
<?xml version="1.0" encoding="UTF-8"?>
<TestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XPath.xsd">
  <Entry Expr="A/B/*">
    <Tokenize>
      <Tok T="NtName" V="A" />
      <Tok T="OpSep" V="/" />
      <Tok T="NtName" V="B" />
      <Tok T="OpSep" V="/" />
      <Tok T="NtAny" V="*" />
    </Tokenize>
    <Parse T="Sep" V="/">
      <L T="Sep" V="/">
        <L T="NodeTest" V="A" />
        <R T="NodeTest" V="B" />
      </L>
      <R T="NodeTest" V="*" />
    </Parse>
    <Compile T="Path">
      <Path T="Context" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="A" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="B" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="" />
    </Compile>
  </Entry>
  <Entry Expr="(A/B)[1]/@*">
    <Tokenize>
      <Tok T="POpen" V="(" />
      <Tok T="NtName" V="A" />
      <Tok T="OpSep" V="/" />
      <Tok T="NtName" V="B" />
      <Tok T="PClose" V=")" />
      <Tok T="BOpen" V="[" />
      <Tok T="Number" V="1" />
      <Tok T="BClose" V="]" />
      <Tok T="OpSep" V="/" />
      <Tok T="Attr" V="@" />
      <Tok T="NtAny" V="*" />
    </Tokenize>
    <Parse T="Sep" V="/">
      <L T="ExprFilter" V="[">
        <L T="Sep" V="/">
          <L T="NodeTest" V="A" />
          <R T="NodeTest" V="B" />
        </L>
        <R T="Value" V="1" />
      </L>
      <R T="Axis" V="@">
        <L T="NodeTest" V="*" />
      </R>
    </Parse>
    <Compile T="Path">
      <Path T="Expr">
        <Expr T="Path">
          <Path T="Context" />
          <Path T="Axis" Ax="Child" Heap="1" />
          <Path T="NameTest" Ns="" N="A" />
          <Path T="Axis" Ax="Child" Heap="1" />
          <Path T="NameTest" Ns="" N="B" />
        </Expr>
      </Path>
      <Path T="Filter">
        <Expr T="Number" Num="1" />
      </Path>
      <Path T="Axis" Ax="Attribute" />
      <Path T="NameTest" Ns="" N="" />
    </Compile>
  </Entry>
  <Entry Expr="(A/B)[@*][1]">
    <Tokenize>
      <Tok T="POpen" V="(" />
      <Tok T="NtName" V="A" />
      <Tok T="OpSep" V="/" />
      <Tok T="NtName" V="B" />
      <Tok T="PClose" V=")" />
      <Tok T="BOpen" V="[" />
      <Tok T="Attr" V="@" />
      <Tok T="NtAny" V="*" />
      <Tok T="BClose" V="]" />
      <Tok T="BOpen" V="[" />
      <Tok T="Number" V="1" />
      <Tok T="BClose" V="]" />
    </Tokenize>
    <Parse T="ExprFilter" V="[">
      <L T="ExprFilter" V="[">
        <L T="Sep" V="/">
          <L T="NodeTest" V="A" />
          <R T="NodeTest" V="B" />
        </L>
        <R T="Axis" V="@">
          <L T="NodeTest" V="*" />
        </R>
      </L>
      <R T="Value" V="1" />
    </Parse>
    <Compile T="Path">
      <Path T="Expr">
        <Expr T="Path">
          <Path T="Expr">
            <Expr T="Path">
              <Path T="Context" />
              <Path T="Axis" Ax="Child" Heap="1" />
              <Path T="NameTest" Ns="" N="A" />
              <Path T="Axis" Ax="Child" Heap="1" />
              <Path T="NameTest" Ns="" N="B" />
            </Expr>
          </Path>
          <Path T="Filter">
            <Expr T="Path">
              <Path T="Context" />
              <Path T="Axis" Ax="Attribute" />
              <Path T="NameTest" Ns="" N="" />
            </Expr>
          </Path>
        </Expr>
      </Path>
      <Path T="Filter">
        <Expr T="Number" Num="1" />
      </Path>
    </Compile>
  </Entry>
  <Entry Expr="A/B[1]/@*">
    <Tokenize>
      <Tok T="NtName" V="A" />
      <Tok T="OpSep" V="/" />
      <Tok T="NtName" V="B" />
      <Tok T="BOpen" V="[" />
      <Tok T="Number" V="1" />
      <Tok T="BClose" V="]" />
      <Tok T="OpSep" V="/" />
      <Tok T="Attr" V="@" />
      <Tok T="NtAny" V="*" />
    </Tokenize>
    <Parse T="Sep" V="/">
      <L T="Sep" V="/">
        <L T="NodeTest" V="A" />
        <R T="PathFilter" V="[">
          <L T="NodeTest" V="B" />
          <R T="Value" V="1" />
        </R>
      </L>
      <R T="Axis" V="@">
        <L T="NodeTest" V="*" />
      </R>
    </Parse>
    <Compile T="Path">
      <Path T="Context" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="A" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="B" />
      <Path T="Filter">
        <Expr T="Number" Num="1" />
      </Path>
      <Path T="Axis" Ax="Attribute" />
      <Path T="NameTest" Ns="" N="" />
    </Compile>
  </Entry>
  <Entry Expr="A/child::B[1]/@*">
    <Tokenize>
      <Tok T="NtName" V="A" />
      <Tok T="OpSep" V="/" />
      <Tok T="AxisName" V="child" />
      <Tok T="Axis" V="::" />
      <Tok T="NtName" V="B" />
      <Tok T="BOpen" V="[" />
      <Tok T="Number" V="1" />
      <Tok T="BClose" V="]" />
      <Tok T="OpSep" V="/" />
      <Tok T="Attr" V="@" />
      <Tok T="NtAny" V="*" />
    </Tokenize>
    <Parse T="Sep" V="/">
      <L T="Sep" V="/">
        <L T="NodeTest" V="A" />
        <R T="PathFilter" V="[">
          <L T="Axis" V="child">
            <L T="NodeTest" V="B" />
          </L>
          <R T="Value" V="1" />
        </R>
      </L>
      <R T="Axis" V="@">
        <L T="NodeTest" V="*" />
      </R>
    </Parse>
    <Compile T="Path">
      <Path T="Context" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="A" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="B" />
      <Path T="Filter">
        <Expr T="Number" Num="1" />
      </Path>
      <Path T="Axis" Ax="Attribute" />
      <Path T="NameTest" Ns="" N="" />
    </Compile>
  </Entry>
  <Entry Expr="A/B[sum(C/@V)=15]">
    <Tokenize>
      <Tok T="NtName" V="A" />
      <Tok T="OpSep" V="/" />
      <Tok T="NtName" V="B" />
      <Tok T="BOpen" V="[" />
      <Tok T="FuncName" V="sum" />
      <Tok T="POpen" V="(" />
      <Tok T="NtName" V="C" />
      <Tok T="OpSep" V="/" />
      <Tok T="Attr" V="@" />
      <Tok T="NtName" V="V" />
      <Tok T="PClose" V=")" />
      <Tok T="OpEq" V="=" />
      <Tok T="Number" V="15" />
      <Tok T="BClose" V="]" />
    </Tokenize>
    <Parse T="Sep" V="/">
      <L T="NodeTest" V="A" />
      <R T="PathFilter" V="[">
        <L T="NodeTest" V="B" />
        <R T="CompareOp" V="=">
          <L T="FuncCall" V="sum">
            <L T="Sep" V="/">
              <L T="NodeTest" V="C" />
              <R T="Axis" V="@">
                <L T="NodeTest" V="V" />
              </R>
            </L>
          </L>
          <R T="Value" V="15" />
        </R>
      </R>
    </Parse>
    <Compile T="Path">
      <Path T="Context" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="A" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="B" />
      <Path T="Filter">
        <Expr T="Eq">
          <L T="Func">
            <Arg T="Path">
              <Path T="Context" />
              <Path T="Axis" Ax="Child" Heap="1" />
              <Path T="NameTest" Ns="" N="C" />
              <Path T="Axis" Ax="Attribute" />
              <Path T="NameTest" Ns="" N="V" />
            </Arg>
          </L>
          <R T="Number" Num="15" />
        </Expr>
      </Path>
    </Compile>
  </Entry>
  <Entry Expr="//B/preceding::*//*">
    <Tokenize>
      <Tok T="OpSepDesc" V="//" />
      <Tok T="NtName" V="B" />
      <Tok T="OpSep" V="/" />
      <Tok T="AxisName" V="preceding" />
      <Tok T="Axis" V="::" />
      <Tok T="NtAny" V="*" />
      <Tok T="OpSepDesc" V="//" />
      <Tok T="NtAny" V="*" />
    </Tokenize>
    <Compile T="Path">
      <Path T="Root" />
      <Path T="Axis" Ax="DescendantOrSelf" Heap="1" Dd="1" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="B" Rev="1" />
      <Path T="Axis" Ax="Preceding" Heap="1" Fwd="0" />
      <Path T="NameTest" Ns="" N="" Fwd="0" Dd="1" Rev="1" />
      <Path T="Axis" Ax="DescendantOrSelf" Heap="1" Dd="1" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="" />
    </Compile>
  </Entry>
  <Entry Expr=".=1">
    <Tokenize>
      <Tok T="Self" V="." />
      <Tok T="OpEq" V="=" />
      <Tok T="Number" V="1" />
    </Tokenize>
    <Compile T="Eq">
      <L T="Path">
        <Path T="Context" />
        <Path T="Axis" Ax="Self" />
      </L>
      <R T="Number" Num="1" />
    </Compile>
  </Entry>
  <Entry Expr="A/B[3]/C[2]/preceding::*">
    <Compile T="Path">
      <Path T="Context" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="A" />
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="B" />
      <Path T="Filter">
        <Expr T="Number" Num="3" />
      </Path>
      <Path T="Axis" Ax="Child" Heap="1" />
      <Path T="NameTest" Ns="" N="C" />
      <Path T="Filter" Rev="1">
        <Expr T="Number" Num="2" />
      </Path>
      <Path T="Axis" Ax="Preceding" Fwd="0" Heap="1" />
      <Path T="NameTest" Ns="" N="" Fwd="0" Rev="1" Dd="1" />
    </Compile>
  </Entry>
</TestData>
